version: 1
type: "singlenode"
worker:
  container: "tensorflow/tensorflow:1.13.1-py3"
  command: "pip install -r requirements.txt && python train.py"
  machine-type: "G1"
model:
  type: Sklearn
  path: '/artifacts'