version: 2

workflows:
  single-node:
    steps:
      -
        name: "single-node"
        command: experiment.run_single_node
        params:
          command: pip install -r requirements.txt && python train.py
          container: tensorflow/tensorflow:1.13.1-gpu-py3
          machineType: "C3"